[project]
name = "ansible-stow"
version = "1.2.1"
description = "Ansible module that interacts with GNU Stow packages"
authors = [{ name = "Caian Ertl", email = "hi@caian.org" }]
license = { text = "CC0-1.0" }
requires-python = ">=3.10,<4.0"
classifiers = [
    # Trove classifiers
    # Full list: https://pypi.python.org/pypi?%3Aaction=list_classifiers
    "Environment :: Console",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "License :: CC0 1.0 Universal (CC0 1.0) Public Domain Dedication",
]
dependencies = [
    "ansible==9.7.0",
]

[project.optional-dependencies]
dev = [
    "bandit==1.9.3",
    "black==24.4.2",
    "poethepoet==0.27.0",
    "pylint==3.2.5",
    "vulture==2.11",
]

[project.urls]
Homepage = "https://github.com/caian-org/ansible-stow"
Repository = "https://github.com/caian-org/ansible-stow"

[tool.poe.tasks]
"fix:style"      = "black -l 120 -S stow.py"
"check:deadcode" = "vulture stow.py"
"check:lint"     = "pylint --fail-under 9 --rcfile .pylintrc --output-format colorized --verbose stow.py"
"check:style"    = "black -l 120 -S --check stow.py"
"check:security" = "bandit -r stow.py"

[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"
