name: Code quality checks

on:
  push:
    branches:
      - '*'
    tags:
      - '*'
    paths-ignore:
      - '**.md'

  pull_request:
    branches:
      - '*'
    paths-ignore:
      - '**.md'

jobs:
  code-check:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Cache uv
        id: code-check-cache
        uses: actions/cache@v5
        with:
          path: |
            .venv
            ~/.cache/uv
          key: code-check-python-${{ hashFiles('**/uv.lock') }}

      - name: Install dependencies
        if: steps.code-check-cache.outputs.cache-hit != 'true'
        run: uv sync --extra dev --frozen

      - name: Check code style
        run: uv run poe check:style

      - name: Check lint
        run: uv run poe check:lint

      - name: Check security issues
        run: uv run poe check:security

      - name: Check for dead code
        run: uv run poe check:deadcode

      - name: Check shell scripts
        run: |
          sudo apt-get install -y shellcheck
          shellcheck tests/test.sh
